### ISSUE TITLE
DataTables

### ISSUE THREAD

**Issue by D-Bits** [D-Bits/COVID-19-Tracker#2]
Get DataTables.js working.

**Comment by farhadmpr** [comment]
Hello @D-Bits , May I work on this?
If so, please assign me.

**Comment by D-Bits** [comment]
Hi Farhad,

Thanks for offering your help. However, this issue has since been more-or-less solved. I apologise for being late on updating the project issues. That said, if there's something else you would like to work on in regards to this project, please let me know.

Sincerely, 

Dana
